packages:
  - apps/*
  - apps/*/ui
  - packages/*

catalog:
  '@bufbuild/protobuf': ^2.11.0
  '@connectrpc/connect': ^2.1.1
  '@connectrpc/connect-express': ^2.1.1
  '@connectrpc/connect-node': ^2.1.1
  '@connectrpc/connect-web': ^2.1.1
  '@jsonforms/core': ^3.7.0
  '@jsonforms/vue': ^3.7.0
  '@jsonforms/vue-vanilla': ^3.7.0
  '@jsonforms/vue-vuetify': ^3.7.0
  vue: ^3.5.27
  vuetify: ^3.11.8

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@parcel/watcher'
  - esbuild
  - vue-demi
