name: Build and Publish Docker Image

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Install backend dependencies
        run: pnpm install
      
      - name: Install frontend dependencies
        run: cd ui && pnpm install
      
      - name: Build backend
        run: pnpm run build
      
      - name: Build frontend
        run: cd ui && pnpm run build
      
      - name: Verify build artifacts
        run: |
          ls -la dist/
          ls -la public/
  
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate version tag
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "tag=${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Gitea Container Registry
        run: |
          echo "${{ secrets.GIT_PAT }}" | docker login git.rokkon.com -u "${{ secrets.GIT_USER }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t git.rokkon.com/io-pipeline/platform-shell:${{ steps.version.outputs.tag }} \
                       -t git.rokkon.com/io-pipeline/platform-shell:latest \
                       .

      - name: Test Docker image
        run: |
          # Clean up any existing test container
          docker rm -f test-shell 2>/dev/null || true

          docker run -d --name test-shell -p 38106:38106 git.rokkon.com/io-pipeline/platform-shell:latest
          echo "Waiting for container to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:38106/ >/dev/null 2>&1; then
              echo "Container is ready!"
              break
            fi
            echo "Attempt $i/30: Container not ready yet..."
            sleep 1
          done
          curl -f http://localhost:38106/ || (docker logs test-shell && exit 1)

          # Clean up
          docker stop test-shell
          docker rm test-shell

      - name: Push to Gitea Container Registry
        run: |
          docker push git.rokkon.com/io-pipeline/platform-shell:${{ steps.version.outputs.tag }}
          docker push git.rokkon.com/io-pipeline/platform-shell:latest

